spring.application.name=backend

# 1. FORÇA O SPRING A LER O FICHEIRO .ENV NA RAIZ DO PROJETO
spring.config.import=optional:file:.env

# 2. Ligação com o seu MySQL Local (Sintaxe correta com chavetas)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# 3. Configurações do Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 4. Configuração do Token JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}